[tool.poetry]
name = "hypothesis-graphql"
version = "0.6.1"
description = "Hypothesis strategies for GraphQL schemas and queries"
keywords = ["hypothesis", "graphql", "testing"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Framework :: Hypothesis",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development :: Testing",
]
authors = ["Dmitry Dygalo <dadygalo@gmail.com>"]
readme = "README.rst"
repository = "https://github.com/Stranger6667/hypothesis-graphql"
license = "MIT"
include = ["src/hypothesis_graphql/py.typed"]

[tool.poetry.dependencies]
python = "^3.6"
hypothesis = ">5.8.0"
graphql-core = "^3.1.0"
attrs = ">20.3.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"

[tool.black]
line-length = 120
target_version = ["py37"]

[tool.isort]
line_length = 120
multi_line_output = 3
default_section = "THIRDPARTY"
include_trailing_comma = true
known_first_party = "hypothesis_graphql"
known_third_party =["attr", "graphql", "hypothesis", "hypothesis_graphql", "pytest"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
