name: Update prek

on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  release:
    name: Update prek
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 1
          submodules: true

      - uses: astral-sh/setup-uv@v7

      - run: uv tool install prek
      - run: prek autoupdate

      - name: Open pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          title: Update prek
          body: Automatically update prek hooks
          commit-message: 'chore: Update prek'
          committer: 'Stranger6667 <dmitry@dygalo.dev>'
          author: 'Stranger6667 <dmitry@dygalo.dev>'
          branch: "create-pull-request/update-prek"
